#!/usr/bin/env python3
"""
gen_config.py – Mini-AUTOSAR FLA Configuration Code Generator
==============================================================
Reads config/ecu_config.yaml and generates:
  src/bsw/Dio_Cfg.h   – DIO channel symbolic names + direction table
  src/rte/Rte_Cfg.h   – RTE port-to-channel mapping + scheduler periods

This mimics what DaVinci Configurator / EB Tresos does in a real project.
Usage:
    python3 scripts/gen_config.py [--config config/ecu_config.yaml]
"""

import argparse
import sys
import os
from datetime import datetime

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(1)

# ── Template helpers ────────────────────────────────────────────────

BANNER = """\
/**
 * @file    {filename}
 * @brief   {brief}
 *
 * *** AUTO-GENERATED BY scripts/gen_config.py ***
 * *** Source: {source}           ***
 * *** Date:   {date}             ***
 * *** DO NOT EDIT MANUALLY – regenerate with: python3 scripts/gen_config.py ***
 */
"""

def guard_open(name: str) -> str:
    macro = name.replace(".", "_").upper()
    return f"#ifndef {macro}\n#define {macro}\n"

def guard_close(name: str) -> str:
    macro = name.replace(".", "_").upper()
    return f"\n#endif /* {macro} */\n"


# ── Generators ─────────────────────────────────────────────────────

def gen_dio_cfg(config: dict) -> str:
    channels = config["dio_channels"]
    lines = []

    lines.append(BANNER.format(
        filename="Dio_Cfg.h",
        brief="Mini-AUTOSAR BSW – DIO configuration",
        source="config/ecu_config.yaml",
        date=datetime.now().strftime("%Y-%m-%d")
    ))
    lines.append(guard_open("Dio_Cfg.h"))
    lines.append('\n#include "../mcal/Mcal_Dio.h"\n')

    lines.append("\n/* ------------------------------------------------------------------")
    lines.append(" *  Symbolic channel names → physical MCAL channel IDs")
    lines.append(" * ------------------------------------------------------------------ */")
    for ch in channels:
        macro = f"DIO_CHANNEL_{ch['name']}"
        lines.append(f"#define {macro:<35} ((Mcal_Dio_ChannelType){ch['channel']}u)"
                     f"  /* {ch.get('description', '')} */")

    # Build direction table
    max_ch = max(ch["channel"] for ch in channels)
    dir_table = [1] * (max_ch + 1)  # default OUTPUT
    # Set declared channels
    for ch in channels:
        dir_table[ch["channel"]] = 0 if ch["direction"] == "INPUT" else 1
    # Pad to MCAL_DIO_NUM_CHANNELS
    while len(dir_table) < 8:
        dir_table.append(1)

    dir_str = ", ".join(f"{d}u" for d in dir_table)
    lines.append("\n/* Direction table: INPUT=0  OUTPUT=1 (index = channel) */")
    lines.append(f"#define DIO_CFG_DIRECTIONS {{ {dir_str} }}")

    lines.append(guard_close("Dio_Cfg.h"))
    return "\n".join(lines)


def gen_rte_cfg(config: dict) -> str:
    channels = {ch["name"]: ch["channel"] for ch in config["dio_channels"]}
    ports    = config["rte_ports"]
    sched    = config["scheduler"]
    lines    = []

    lines.append(BANNER.format(
        filename="Rte_Cfg.h",
        brief="Mini-AUTOSAR RTE – Port/Signal configuration",
        source="config/ecu_config.yaml",
        date=datetime.now().strftime("%Y-%m-%d")
    ))
    lines.append(guard_open("Rte_Cfg.h"))
    lines.append('\n#include "../bsw/Dio.h"')
    lines.append('#include "../bsw/Gpt.h"')

    lines.append("\n/* ------------------------------------------------------------------")
    lines.append(" *  Signal → Physical channel mapping")
    lines.append(" * ------------------------------------------------------------------ */")

    for swc, port_map in ports.items():
        lines.append(f"\n/* {swc} */")
        for port_name, ch_name in port_map.items():
            macro = f"RTE_CFG_{ch_name}_CHANNEL"
            dio_macro = f"DIO_CHANNEL_{ch_name}"
            lines.append(f"#define {macro:<40} {dio_macro}")

    lines.append("\n/* ------------------------------------------------------------------")
    lines.append(" *  Scheduler timing (ticks, 1 tick = 1 ms)")
    lines.append(" * ------------------------------------------------------------------ */")
    for key, value in sched.items():
        macro = f"RTE_CFG_TASK_PERIOD_{key.upper()}"
        lines.append(f"#define {macro:<55} {value}u")

    lines.append(guard_close("Rte_Cfg.h"))
    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Mini-AUTOSAR config generator")
    parser.add_argument("--config", default="config/ecu_config.yaml",
                        help="Path to ecu_config.yaml")
    parser.add_argument("--out-bsw", default="src/bsw/Dio_Cfg.h",
                        help="Output path for Dio_Cfg.h")
    parser.add_argument("--out-rte", default="src/rte/Rte_Cfg.h",
                        help="Output path for Rte_Cfg.h")
    args = parser.parse_args()

    # Load YAML
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    config_path = os.path.join(project_root, args.config)

    print(f"[gen_config] Reading {config_path} ...")
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    # Generate Dio_Cfg.h
    dio_path = os.path.join(project_root, args.out_bsw)
    os.makedirs(os.path.dirname(dio_path), exist_ok=True)
    with open(dio_path, "w") as f:
        f.write(gen_dio_cfg(config))
    print(f"[gen_config] Generated {args.out_bsw}")

    # Generate Rte_Cfg.h
    rte_path = os.path.join(project_root, args.out_rte)
    os.makedirs(os.path.dirname(rte_path), exist_ok=True)
    with open(rte_path, "w") as f:
        f.write(gen_rte_cfg(config))
    print(f"[gen_config] Generated {args.out_rte}")

    print("[gen_config] Done. Rebuild project to pick up new configuration.")


if __name__ == "__main__":
    main()
