/**
 * @file    Dio_Cfg.h
 * @brief   Mini-AUTOSAR BSW – DIO configuration (auto-generated from ecu_config.yaml)
 * @note    In a real toolchain this file is generated by DaVinci or EB Tresos.
 *          Here it is generated by scripts/gen_config.py from config/ecu_config.yaml.
 *
 * *** DO NOT EDIT BY HAND – regenerate with: python3 scripts/gen_config.py ***
 */
#ifndef DIO_CFG_H
#define DIO_CFG_H

#include "../mcal/Mcal_Dio.h"

/* ------------------------------------------------------------------
 *  Symbolic channel names → physical MCAL channel IDs
 *  Changing a physical pin only requires updating ecu_config.yaml
 *  and re-running gen_config.py.  Application code is untouched.
 * ------------------------------------------------------------------ */
#define DIO_CHANNEL_BUTTON_0        ((Mcal_Dio_ChannelType)0u)
#define DIO_CHANNEL_BUTTON_1        ((Mcal_Dio_ChannelType)1u)
#define DIO_CHANNEL_LED_STATUS      ((Mcal_Dio_ChannelType)2u)
#define DIO_CHANNEL_LED_BLINK       ((Mcal_Dio_ChannelType)3u)
#define DIO_CHANNEL_LED_HEARTBEAT   ((Mcal_Dio_ChannelType)4u)

/* Direction: INPUT=0 OUTPUT=1 */
#define DIO_CFG_DIRECTIONS { 0u, 0u, 1u, 1u, 1u, 1u, 1u, 1u }

#endif /* DIO_CFG_H */
